import { isDefined } from 'twenty-shared/utils';

const extractStringField = (
  record: Record<string, unknown> | undefined,
  fieldName: string,
): string | null => {
  if (!isDefined(record)) {
    return null;
  }

  const value = record[fieldName];

  return typeof value === 'string' && value.length > 0 ? value : null;
};

// Reads the target record id of a MANY_TO_ONE relation from a raw create/update
// payload, regardless of the shape the caller used:
//   - the join column directly: { internalEntityId: '...' }
//   - a resolved nested object: { internalEntity: { id: '...' } }
//   - the GraphQL relation-connect input generated by
//     RelationConnectGqlInputTypeGenerator: { internalEntity: { connect: { where: { id: '...' } } } }
//   - the flatter { internalEntity: { connect: { id: '...' } } } some internal
//     callers use directly (not GraphQL-generated, kept for compatibility).
export const extractRelationTargetId = (
  record: Record<string, unknown> | undefined,
  relationFieldName: string,
  joinColumnFieldName: string,
): string | null => {
  const joinColumnValue = extractStringField(record, joinColumnFieldName);

  if (isDefined(joinColumnValue)) {
    return joinColumnValue;
  }

  if (!isDefined(record)) {
    return null;
  }

  const relationFieldValue = record[relationFieldName];

  if (
    typeof relationFieldValue !== 'object' ||
    relationFieldValue === null ||
    Array.isArray(relationFieldValue)
  ) {
    return null;
  }

  const directId = extractStringField(
    relationFieldValue as Record<string, unknown>,
    'id',
  );

  if (isDefined(directId)) {
    return directId;
  }

  const connectValue = (relationFieldValue as Record<string, unknown>).connect;

  if (
    typeof connectValue !== 'object' ||
    connectValue === null ||
    Array.isArray(connectValue)
  ) {
    return null;
  }

  const connectId = extractStringField(
    connectValue as Record<string, unknown>,
    'id',
  );

  if (isDefined(connectId)) {
    return connectId;
  }

  const whereValue = (connectValue as Record<string, unknown>).where;

  if (
    typeof whereValue !== 'object' ||
    whereValue === null ||
    Array.isArray(whereValue)
  ) {
    return null;
  }

  return extractStringField(whereValue as Record<string, unknown>, 'id');
};
