export const ONBOARDING_SUPERADMIN_WORKSPACE_SETUP_PENDING =
  'ONBOARDING_SUPERADMIN_WORKSPACE_SETUP_PENDING';

export const ONBOARDING_SUPERADMIN_WORKSPACE_SETUP_STATE =
  'ONBOARDING_SUPERADMIN_WORKSPACE_SETUP_STATE';
